export const CHANGE_INPUT      = 'Signup/CHANGE_INPUT'
export const SIGNUP_CALLING    = 'Signup/SIGNUP_CALLING'
export const SIGNUP_RECEIVE    = 'Signup/SIGNUP_RECEIVE'
export const SIGNUP_SUCCESS    = 'Signup/SIGNUP_SUCCESS'
export const SIGNUP_ERROR      = 'Signup/SIGNUP_ERROR'
export const SIGNUP_VALIDATION = 'Signup/SIGNUP_VALIDATION'
