export const CHANGE_INPUT    = 'Login/CHANGE_INPUT'
export const AUTH_CALLING    = 'Login/AUTH_CALLING'
export const AUTH_RECEIVE    = 'Login/AUTH_RECEIVE'
export const AUTH_SUCCESS    = 'Login/AUTH_SUCCESS'
export const AUTH_ERROR      = 'Login/AUTH_ERROR'
export const AUTH_VALIDATION = 'Login/AUTH_VALIDATION'
