export const CHANGE_INPUT   = 'Profile/CHANGE_INPUT'
export const UPDATE_CALLING = 'Profile/UPDATE_CALLING'
export const UPDATE_RECEIVE = 'Profile/UPDATE_RECEIVE'
export const UPDATE_SUCCESS = 'Profile/UPDATE_SUCCESS'
export const UPDATE_ERROR   = 'Profile/UPDATE_ERROR'
