export const apiStatuses = {
  NOT_STARTED: 'NOT_STARTED',
  STARTED: 'STARTED',
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
}

export const apiCalls = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_FACEBOOK: 'AUTH_FACEBOOK',
  MEDITATIONS_LOAD: 'MEDITATIONS_LOAD',
  MEDITATIONS_LEAVE: 'MEDITATIONS_LEAVE',
  MEDITATIONS_ENTER: 'MEDITATIONS_ENTER',
  PROFILE_LOAD: 'PROFILE_LOAD',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  NOTIFICATIONS_LOAD: 'NOTIFICATIONS_LOAD',
  NOTIFICATIONS_CREATE: 'NOTIFICATIONS_CREATE'
}

export const actions = {
  API_STATUS_CHANGE: 'API_STATUS_CHANGE',
}