export const NOTIFICATION_CALLING = 'Session/NOTIFICATION_CALLING'
export const NOTIFICATION_RECEIVE = 'Session/NOTIFICATION_RECEIVE'
export const NOTIFICATION_SUCCESS = 'Session/NOTIFICATION_SUCCESS'
export const NOTIFICATION_ERROR   = 'Session/NOTIFICATION_ERROR'
